THORSANVIL_ROOT             = $(realpath ../../)

TARGET                      = ThorsGraphic.slib
CXXFLAGS					+= $(SDL_CFLAGS)
LDLIBS						+= $(SDL_LIBS)
LINK_LIBS					+= ThorsSDL

UNITTEST_LINK_LIBS			+= ThorsSDL

include $(THORSANVIL_ROOT)/build/tools/Makefile
