THORSANVIL_ROOT             = $(realpath ../../)

TARGET                      = ThorsUI.slib
CXXFLAGS					+= $(SDL_CFLAGS)
LDLIBS						+= $(SDL_LIBS)
COVERAGE_REQUIRED			= 2

include $(THORSANVIL_ROOT)/build/tools/Makefile
