THORSANVIL_ROOT             = $(realpath ../../../)

LINK_LIBS					+= ThorsSDL ThorsGraphics
CXXFLAGS					+= $(SDL_CFLAGS)
LDLIBS						+= $(SDL_LIBS)
TARGET                      = pong.app

include $(THORSANVIL_ROOT)/build/tools/Makefile
