THORSANVIL_ROOT             = $(realpath ../../)

TARGET                      = ThorsSDL.slib
CXXFLAGS					+= $(SDL_CFLAGS)
LDLIBS						+= $(SDL_LIBS) -lSDL2_ttf
COVERAGE_REQUIRED			= 2

include $(THORSANVIL_ROOT)/build/tools/Makefile
