THORSANVIL_ROOT             = $(realpath ../../)

TARGET                      = ThorsSDL.slib
CXX_FLAGS					+= $(SDL_CFLAGS)
LD_LIBS						+= $(SDL_LIBS)

include $(THORSANVIL_ROOT)/build/tools/Makefile
