#include "gtest/gtest.h"
#include "test/ApplicationTest.h"

HANDLER_TEST(JoyMotion, SDL_JoyAxisEvent, SDL_JOYAXISMOTION)
HANDLER_TEST(JoyBall, SDL_JoyBallEvent, SDL_JOYBALLMOTION)
HANDLER_TEST(JoyHat, SDL_JoyHatEvent, SDL_JOYHATMOTION)
HANDLER_TEST(JoyButtonDown, SDL_JoyButtonEvent, SDL_JOYBUTTONDOWN)
HANDLER_TEST(JoyButtonUp, SDL_JoyButtonEvent, SDL_JOYBUTTONUP)
HANDLER_TEST(JoyDeviceAdd, SDL_JoyDeviceEvent, SDL_JOYDEVICEADDED)
HANDLER_TEST(JoyDeviceRem, SDL_JoyDeviceEvent, SDL_JOYDEVICEREMOVED)
HANDLER_TEST(JoyBattery, SDL_JoyBatteryEvent, SDL_JOYBATTERYUPDATED)

