#include "test/WindowTest.h"

WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowShow, SDL_WindowEvent, SDL_WINDOWEVENT_SHOWN)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowHide, SDL_WindowEvent, SDL_WINDOWEVENT_HIDDEN)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowExpose, SDL_WindowEvent, SDL_WINDOWEVENT_EXPOSED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowMoved, SDL_WindowEvent, SDL_WINDOWEVENT_MOVED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowResized, SDL_WindowEvent, SDL_WINDOWEVENT_RESIZED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowSizeChange, SDL_WindowEvent, SDL_WINDOWEVENT_SIZE_CHANGED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowMin, SDL_WindowEvent, SDL_WINDOWEVENT_MINIMIZED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowMax, SDL_WindowEvent, SDL_WINDOWEVENT_MAXIMIZED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowRestore, SDL_WindowEvent, SDL_WINDOWEVENT_RESTORED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowEnter, SDL_WindowEvent, SDL_WINDOWEVENT_ENTER)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowLeave, SDL_WindowEvent, SDL_WINDOWEVENT_LEAVE)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowFocusGain, SDL_WindowEvent, SDL_WINDOWEVENT_FOCUS_GAINED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowFocusLost, SDL_WindowEvent, SDL_WINDOWEVENT_FOCUS_LOST)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowClose, SDL_WindowEvent, SDL_WINDOWEVENT_CLOSE)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowTakeFocus, SDL_WindowEvent, SDL_WINDOWEVENT_TAKE_FOCUS)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowHitTest, SDL_WindowEvent, SDL_WINDOWEVENT_HIT_TEST)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowICCProfChange, SDL_WindowEvent, SDL_WINDOWEVENT_ICCPROF_CHANGED)
WIN_HANDLER_WIN_TEST(Window_WindowEventsTest, WindowDisplayChange, SDL_WindowEvent, SDL_WINDOWEVENT_DISPLAY_CHANGED)


