THORSANVIL_ROOT             = $(realpath ../../)

TARGET                      = ThorsWidgets.slib
CXXFLAGS					+= $(SDL_CFLAGS)
LDLIBS						+= $(SDL_LIBS)
LINKLIBS					+= ThorsSDL

include $(THORSANVIL_ROOT)/build/tools/Makefile
